  name: docs

  on:
    push:
      branches: ["master"]

  permissions:
    contents: read

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: dtolnay/rust-toolchain@stable

        - name: Cache Rust
          uses: Swatinem/rust-cache@v2

        - name: Build docs
          run: |
            cargo doc --no-deps --document-private-items

        - name: Deployment summary
          run: |
            echo "Successfully deployed docs"
