  name: docs

  on:
    push:
      branches: ["master"]

  permissions:
    contents: read

  env:
    DOCS_HOST: ${{ secrets.DOCS_HOST }}

  jobs:
    deploy:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4

        - uses: dtolnay/rust-toolchain@stable

        - name: Cache Rust
          uses: Swatinem/rust-cache@v2

        - name: Build docs
          run: |
            cargo doc --no-deps --document-private-items
            cargo doc -p secapi_client --no-deps --document-private-items

        - name: Deploy docs
          run: |
            rsync -avz --delete target/doc/ netxp@${DOCS_HOST}:/var/www/docs/IRIS-rs

        - name: Deployment summary
          run: |
            echo "Successfully deployed docs"
